{% set name = "webargs" %}
{% set version = "8.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8d098ab92bd74c659eca705afa31d681475f218cb15c1e57271fa2103c0547a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core <4
  run:
    - python >={{ python_min }}
    - marshmallow >=3.0.0
    - packaging >=17.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - webargs

about:
  home: https://github.com/marshmallow-code/webargs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A friendly library for parsing HTTP request arguments, with built-in support for popular web frameworks

  description: |
    webargs is a Python library for parsing HTTP request arguments, with
    built-in support for popular web frameworks, including Flask, Django,
    Bottle, Tornado, Pyramid, webapp2, Falcon, and aiohttp.
  doc_url: http://webargs.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/webargs

extra:
  recipe-maintainers:
    - frol
    - synapticarbors
